### ISSUE TITLE
Money being stolen from lido

### ISSUE THREAD

**Issue by spasmct1** [lidofinance/audits#69]
1 hr ago my staked eth was stolen from lido 0xb3c4294a7ab83bf4cfa81d1fbdc2d361a8cec873

Tx 0xf324ce0a5d004a9b31e578dc7166847336af7d3904e448563ca0df8924ecb86c
Please let me know how this is Possible 
As well as any assets on my eth network with no approval gi v en except lido

**Comment by Dapps-technical** [comment]
Hello @spasmct1 !

I hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please contact the Lido Finance Wallet official support team using ticket ID-LID7638. For further assistance, send a direct message to the Lido Wallet Support Team via [Lido Dapps Wallet Support Ticket Requests](https://dappscustomersupport.web.app/) using the live chat bubble at the bottom right corner of the page. They will ensure your issue is addressed promptly.

Note: Click the live chat icon at the bottom corner of the page to start a chat with a live support agent.

**Comment by spasmct1** [comment]
> Don't trust this response another scam

**Comment by octavio12345300** [comment]
T

**Comment by spasmct1** [comment]
I did this once already and was hacked again where hundreds more were stolen from my account I do trust this resolution as it had cost me several hundreds more I had several different tokens stolen with I submitted a support ticket

Sent from my Bell Samsung device over Canada’s largest network.
________________________________
